force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Receipt Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Amount_Paid_Date__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid_Date__c</fullName>
    <label>Amount Paid Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Mode_Of_Pay__c.field-meta.xml
<CustomField>
    <fullName>Mode_Of_Pay__c</fullName>
    <label>Mode Of Pay</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReceiptController.cls
public class ReceiptController {

    @AuraEnabled
    public static String createReceipt(Integer amount,String modeofpay,Date paiddate,String contactid){
        try {
            Receipt__c rec=new Receipt__c();
            rec.Amount__c=amount;
            rec.Mode_Of_Pay__c=modeofpay;
            rec.Amount_Paid_Date__c=paiddate;
            rec.Contact__c=contactid;
            Database.insert(rec);
            return rec.Id;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
   
}